version: '3.8'

services:
  ai-langchain-db:
    image: pgvector/pgvector:pg18-trixie
    container_name: ai-langchain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_langchain_db
    ports:
      - "5435:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d

networks:
  default:
    name: ai-langchain-network
    driver: bridge
